name: dj_pmi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter_local_notifications: ^18.0.0
  flutter_svg: ^2.0.16
  get_it: ^8.0.2
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.2
  intl: any
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_gen: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.8.0
  lint:

flutter:
  uses-material-design: true
  generate: false

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/illustrations/
    - assets/fonts/

  fonts:
    - family: Inter Tight
      fonts:
        - asset: assets/fonts/InterTight-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterTight-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600

flutter_gen:
  output: lib/common/gen/
  line_length: 120

  integrations:
    flutter_svg: true

  assets:
    class_name: dj_pmiAssets
